### ISSUE TITLE
Update versions and requirements

### ISSUE THREAD

**Issue by jcdouglas** [Kastervo/OpenVAS-Installation#2]
Got an error with libcurl showing in red as it scrolled by on running script, added the package 'libcurl4-openssl-dev' to one of the apt install lines.

Versions also need to be updated otherwise Greenbone spits out messages about not having the latest:

export GVM_LIBS_VERSION=22.9.1
export GVMD_VERSION=23.6.2
export PG_GVM_VERSION=22.6.5
export GSA_VERSION=23.0.0
export GSAD_VERSION=22.9.1
export OPENVAS_SMB_VERSION=22.5.6
export OPENVAS_SCANNER_VERSION=23.4.0
export OSPD_OPENVAS_VERSION=22.7.1
export NOTUS_VERSION=22.6.3

**Comment by jeanfrancois42pin** [comment]
Hello
Thanks for you code
Can you help me ?
I have a problem to install openVAS on debian 12 bookworm.

I don't understand why the debian source with ` http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3  Échec de la connexion [IP : 199.232.170.132 80]`
doesn't run.

root@debian-0000:~# apt update
Atteint :1 http://security.debian.org/debian-security bookworm-security InRelease
Atteint :2 http://deb.debian.org/debian bookworm InRelease
Atteint :3 http://deb.debian.org/debian bookworm-updates InRelease
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Tous les paquets sont à jour.
root@debian-0000:~# 
root@debian-0000:~# apt-get dist-upgrade
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Calcul de la mise à jour... Fait
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
root@debian-0000:~# 


Paquets suggérés :
  bison-doc doc-base gcc-12-locales heimdal-docs libjson-glib-doc liblinear-tools liblinear-dev m4-doc wine wine64 ncat ndiff zenmap perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl libtap-harness-archive-perl
  systemd-container systemd-homed systemd-userdbd systemd-boot systemd-resolved libqrencode4 libtss2-esys-3.0.2-0 libtss2-mu0 libtss2-rc0 polkitd | policykit-1
Les NOUVEAUX paquets suivants seront installés :
  binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 bison comerr-dev gcc-mingw-w64 gcc-mingw-w64-base gcc-mingw-w64-i686 gcc-mingw-w64-i686-posix gcc-mingw-w64-i686-posix-runtime gcc-mingw-w64-i686-win32
  gcc-mingw-w64-i686-win32-runtime gcc-mingw-w64-x86-64 gcc-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix-runtime gcc-mingw-w64-x86-64-win32 gcc-mingw-w64-x86-64-win32-runtime gir1.2-json-1.0 heimdal-dev heimdal-multidev
  libasn1-8-heimdal libblas3 libgssapi3-heimdal libhcrypto5-heimdal libhdb9-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libjson-glib-1.0-0 libjson-glib-1.0-common libjson-glib-dev libkadm5clnt7-heimdal
  libkadm5srv8-heimdal libkafs0-heimdal libkdc2-heimdal libkrb5-26-heimdal libksba-dev liblinear4 libmariadb3 libmicrohttpd-dev libmicrohttpd12 libnetsnmptrapd40 libotp0-heimdal libpci-dev libpcre3 libpopt-dev libroken19-heimdal
  libsensors-dev libsl0-heimdal libsnmp-dev libsnmp-perl libudev-dev libunistring-dev libwind0-heimdal libwrap0-dev lua-lpeg m4 mariadb-common mingw-w64-common mingw-w64-i686-dev mingw-w64-x86-64-dev mysql-common nmap nmap-common
Les paquets suivants seront mis à jour :
  libnss-systemd libpam-systemd libperl5.36 libsystemd-shared libsystemd0 libudev1 perl perl-base perl-modules-5.36 systemd systemd-sysv systemd-timesyncd udev
13 mis à jour, 63 nouvellement installés, 0 à enlever et 13 non mis à jour.
Il est nécessaire de prendre 6 387 ko/223 Mo dans les archives.
Après cette opération, 1 028 Mo d'espace disque supplémentaires seront utilisés.
Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3                                                                                                                                               
Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3
Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3
Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3
Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3
Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3
Err :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3
  Échec de la connexion [IP : 199.232.170.132 80]
Err :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3
  Échec de la connexion [IP : 199.232.170.132 80]
E: Impossible de récupérer http://deb.debian.org/debian/pool/main/m/mingw-w64/mingw-w64-i686-dev_10.0.0-3_all.deb  Échec de la connexion [IP : 199.232.170.132 80]
E: Impossible de récupérer http://deb.debian.org/debian/pool/main/m/mingw-w64/mingw-w64-x86-64-dev_10.0.0-3_all.deb  Échec de la connexion [IP : 199.232.170.132 80]
E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?`

many thank

kind regards

Jean

**Comment by jcdouglas** [comment]
> Hello Thanks for you code Can you help me ? I have a problem to install openVAS on debian 12 bookworm.
> 
> I don't understand why the debian source with ` http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3 Échec de la connexion [IP : 199.232.170.132 80]` doesn't run.
> 
> root@debian-0000:~# apt update Atteint :1 http://security.debian.org/debian-security bookworm-security InRelease Atteint :2 http://deb.debian.org/debian bookworm InRelease Atteint :3 http://deb.debian.org/debian bookworm-updates InRelease Lecture des listes de paquets... Fait Construction de l'arbre des dépendances... Fait Lecture des informations d'état... Fait Tous les paquets sont à jour. root@debian-0000:~# root@debian-0000:~# apt-get dist-upgrade Lecture des listes de paquets... Fait Construction de l'arbre des dépendances... Fait Lecture des informations d'état... Fait Calcul de la mise à jour... Fait 0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour. root@debian-0000:~#
> 
> Paquets suggérés : bison-doc doc-base gcc-12-locales heimdal-docs libjson-glib-doc liblinear-tools liblinear-dev m4-doc wine wine64 ncat ndiff zenmap perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl libtap-harness-archive-perl systemd-container systemd-homed systemd-userdbd systemd-boot systemd-resolved libqrencode4 libtss2-esys-3.0.2-0 libtss2-mu0 libtss2-rc0 polkitd | policykit-1 Les NOUVEAUX paquets suivants seront installés : binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 bison comerr-dev gcc-mingw-w64 gcc-mingw-w64-base gcc-mingw-w64-i686 gcc-mingw-w64-i686-posix gcc-mingw-w64-i686-posix-runtime gcc-mingw-w64-i686-win32 gcc-mingw-w64-i686-win32-runtime gcc-mingw-w64-x86-64 gcc-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix-runtime gcc-mingw-w64-x86-64-win32 gcc-mingw-w64-x86-64-win32-runtime gir1.2-json-1.0 heimdal-dev heimdal-multidev libasn1-8-heimdal libblas3 libgssapi3-heimdal libhcrypto5-heimdal libhdb9-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libjson-glib-1.0-0 libjson-glib-1.0-common libjson-glib-dev libkadm5clnt7-heimdal libkadm5srv8-heimdal libkafs0-heimdal libkdc2-heimdal libkrb5-26-heimdal libksba-dev liblinear4 libmariadb3 libmicrohttpd-dev libmicrohttpd12 libnetsnmptrapd40 libotp0-heimdal libpci-dev libpcre3 libpopt-dev libroken19-heimdal libsensors-dev libsl0-heimdal libsnmp-dev libsnmp-perl libudev-dev libunistring-dev libwind0-heimdal libwrap0-dev lua-lpeg m4 mariadb-common mingw-w64-common mingw-w64-i686-dev mingw-w64-x86-64-dev mysql-common nmap nmap-common Les paquets suivants seront mis à jour : libnss-systemd libpam-systemd libperl5.36 libsystemd-shared libsystemd0 libudev1 perl perl-base perl-modules-5.36 systemd systemd-sysv systemd-timesyncd udev 13 mis à jour, 63 nouvellement installés, 0 à enlever et 13 non mis à jour. Il est nécessaire de prendre 6 387 ko/223 Mo dans les archives. Après cette opération, 1 028 Mo d'espace disque supplémentaires seront utilisés. Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3 Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3 Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3 Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3 Ign :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3 Ign :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3 Err :1 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-i686-dev all 10.0.0-3 Échec de la connexion [IP : 199.232.170.132 80] Err :2 http://deb.debian.org/debian bookworm/main amd64 mingw-w64-x86-64-dev all 10.0.0-3 Échec de la connexion [IP : 199.232.170.132 80] E: Impossible de récupérer http://deb.debian.org/debian/pool/main/m/mingw-w64/mingw-w64-i686-dev_10.0.0-3_all.deb Échec de la connexion [IP : 199.232.170.132 80] E: Impossible de récupérer http://deb.debian.org/debian/pool/main/m/mingw-w64/mingw-w64-x86-64-dev_10.0.0-3_all.deb Échec de la connexion [IP : 199.232.170.132 80] E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?`
> 
> many thank
> 
> kind regards
> 
> Jean

That looks like a Debian apt repository issue, i.e. unable to connect to server based on the translation.  Have you tried running an "apt-get -f install" ?

**Comment by johnathost** [comment]
We have taken into consideration the version updates and we'll commit a change on the main script once we find a suitable time frame. Thank you for contributing.

**Comment by jeanfrancois42pin** [comment]
thank you very much for your understanding

**Comment by johnathost** [comment]
The versions and requirements have been updated on the newest commit: https://github.com/Kastervo/OpenVAS-Installation/commit/a587fdce0e4472a4e2d5562068cac617cdfaa16b
