### ISSUE TITLE
Also need to add gvm user to sudoers, else ICMPV4 error results

### ISSUE THREAD

**Issue by Queue-Fair** [Kastervo/OpenVAS-Installation#3]
Thank you so much for this script!

The install was successful, and it almost worked for me first time once Postgres had stopped whirring with all the test data, but I found that my scans had a status of Interrupted as soon as they started.  The logs showed error: 

failed to open ICMPV4 socket: operation not permitted

When comparing the script with the official Greenbone instructions, I noticed that the instruction to add the gvm group to sudoers was missing:

sudo visudo

...

# allow users of the gvm group run openvas
%gvm ALL = NOPASSWD: /usr/local/sbin/openvas

I don't think you'll be able to add this to the script (but would be happy to be proved wrong) - do you think you could add it to the steps in the README?   It's what I had to do to get it to work.

Thanks so much again!

**Comment by johnathost** [comment]
Hello and thank you for your kind words! We are glad the script worked for you. We have taken into consideration your comments and we'll review the requested changes on the main script once we find a suitable time frame. Thank you for contributing!

**Comment by johnathost** [comment]
In the newest commit, we've added a configuration for /etc/sudoers to allow the gvm group users to run OpenVAS: https://github.com/Kastervo/OpenVAS-Installation/commit/a587fdce0e4472a4e2d5562068cac617cdfaa16b
